# Project to Explore a sales figures data series

The objective of this notebook is to have a project to play around with, that is practical and can get me some experience in the area and serve as curriculum.

Questions to do in terms of EDA and data preparation:
-General importing, null removal, general cleaning analysis, basic graphical representation, separation of it's 3 logical classes, transformation of these said tables into usable classes and a small non SQL database.

Questions in general regarding to the data:

1. Can we make a preditive analyisis of the time between Order and ship dates based upon the caracteristics of an order?
2. Creating a predictive sales model for the company's sales (maybe divided by state and or product range or line).
3. Make a costumer analyis: which are our best costumeres that we should target more? How can we increase the average spending per order?
4. Make a product line analysis, what are our winner products? What should we bet on? ABC analysis? what to (maybe) discontinue?

Small roadmap for the bros out there on the cleaning and importing that i did:
I based myself on the work of Samruddhi Mhatre https://github.com/SamruddhiMhatre 

When doing all of this, this cheat-sheet will be extremly usefull: https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

-**import**  

-**convert to the correct data types**  Be carefull with dates and currencies. Be open to use open costum functions to do it if the data types are a bit hairy.  

-**Check for null values and handle them**

-**Use the describe and head fucntions to understand what's up in general**

-**Divide the data into logical sub-tables if you find it necessary**

Importing all necessary modules:

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

Let's do our importing:

In [3]:
conversion_dictionary = {"Ship Mode": "string",
                         "Order ID" : "string",
                         "Customer ID" : "string",
                         "Customer Name" : "string",
                         "Segment" : "string",
                         "City" : "string",
                         "State" : "string",
                         "Country" : "string",
                         #"Postal Code" : "int", <- there are some null values here in which where not interested
                         "Region" : "string",
                         "Product ID" : "string",
                         "Category" : "string",
                         "Sub-Category" : "string",
                         "Product Name" : "string"}

sales_data = pd.read_csv("sales_time_series.csv",
                         index_col=[0],
                         dtype=conversion_dictionary)

#It's also necessary to convert the dates and the currencies
sales_data["Order Date"] = pd.to_datetime(sales_data["Order Date"])
sales_data["Ship Date"] = pd.to_datetime(sales_data["Ship Date"])

Now let's check for weird stuff like null values

In [4]:
print(sales_data.isnull().sum()) #<- check for nulls
sales_data[sales_data["Postal Code"].isnull()] #<- shows the actual null values

Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
2235,CA-2018-104066,2018-05-12,2018-10-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5275,CA-2016-162887,2016-07-11,2016-09-11,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8799,US-2017-150140,2017-06-04,2017-10-04,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9147,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9148,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9149,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9387,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9388,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9389,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9390,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9742,CA-2016-117086,2016-08-11,2016-12-11,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90

It seems that the problem is always with the town of Burlington Vermont. As it isn't very hard to correct this, let's palce the correct values.

In [5]:
sales_data["Postal Code"] = sales_data["Postal Code"].fillna(5401) #<- 5401 is the zip code of burlington,  vermont

The null problem is now corrected. Let's we what's generally happening with the data then. Let's also order it by date of order. After that let's print some descriptive statistics.

In [6]:
sales_data.head()
sales_data.sort_values("Order Date")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
541,CA-2015-140795,2015-01-02,2015-03-02,First Class,BD-11500,Bradley Drucker,Consumer,United States,Green Bay,Wisconsin,54302.0,Central,TEC-AC-10001432,Technology,Accessories,Enermax Aurora Lite Keyboard,468.900
5714,US-2015-143707,2015-01-03,2015-05-03,Standard Class,HR-14770,Hallie Redmond,Home Office,United States,New York City,New York,10035.0,East,TEC-PH-10003655,Technology,Phones,Sannysis Cute Owl Design Soft Skin Case Cover ...,5.940
158,CA-2015-104269,2015-01-03,2015-06-03,Second Class,DB-13060,Dave Brooks,Consumer,United States,Seattle,Washington,98115.0,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.568
6549,CA-2015-113880,2015-01-03,2015-05-03,Standard Class,VF-21715,Vicky Freymann,Home Office,United States,Elmhurst,Illinois,60126.0,Central,OFF-PA-10003036,Office Supplies,Paper,"Black Print Carbonless 8 1/2"" x 8 1/4"" Rapid M...",17.472
7950,CA-2015-131009,2015-01-03,2015-05-03,Standard Class,SC-20380,Shahid Collister,Consumer,United States,El Paso,Texas,79907.0,Central,FUR-FU-10001095,Furniture,Furnishings,DAX Black Cherry Wood-Tone Poster Frame,63.552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909,CA-2018-143259,2018-12-30,2019-03-01,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009.0,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776
646,CA-2018-126221,2018-12-30,2019-05-01,Standard Class,CC-12430,Chuck Clark,Home Office,United States,Columbus,Indiana,47201.0,Central,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,209.300
908,CA-2018-143259,2018-12-30,2019-03-01,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009.0,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930
907,CA-2018-143259,2018-12-30,2019-03-01,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009.0,East,FUR-BO-10003441,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",323.136
1298,CA-2018-115427,2018-12-30,2019-03-01,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533.0,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720

In [7]:
sales_data["Sales"].describe()

count     9800.000000
mean       230.769059
std        626.651875
min          0.444000
25%         17.248000
50%         54.490000
75%        210.605000
max      22638.480000
Name: Sales, dtype: float64

In [8]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9800 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   string
 1   Order Date     9800 non-null   datetime64[ns]
 2   Ship Date      9800 non-null   datetime64[ns]
 3   Ship Mode      9800 non-null   string
 4   Customer ID    9800 non-null   string
 5   Customer Name  9800 non-null   string
 6   Segment        9800 non-null   string
 7   Country        9800 non-null   string
 8   City           9800 non-null   string
 9   State          9800 non-null   string
 10  Postal Code    9800 non-null   float64
 11  Region         9800 non-null   string
 12  Product ID     9800 non-null   string
 13  Category       9800 non-null   string
 14  Sub-Category   9800 non-null   string
 15  Product Name   9800 non-null   string
 16  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), string(13)
memory usage: 1.3 MB

By the way the data is structured, i suspect that orders contain more than 1 product. Let's check it by testing uniqueness of values.

In [9]:
sales_data["Order ID"].value_counts()

CA-2018-100111    14
CA-2018-157987    12
US-2017-108504    11
CA-2017-165330    11
CA-2017-105732    10
                  ..
CA-2018-147725     1
CA-2016-150560     1
US-2017-163461     1
CA-2017-140977     1
CA-2018-127621     1
Name: Order ID, Length: 4922, dtype: Int64

Okay, several order ID's repeat themselves, let's try to understand why by isolating these lines.

In [10]:
sales_data[sales_data["Order ID"] == "CA-2018-157987"  ]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1947,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-AR-10000658,Office Supplies,Art,Newell 324,23.100
1948,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,FUR-FU-10001196,Furniture,Furnishings,DAX Cubicle Frames - 8x10,11.540
1949,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,FUR-TA-10001889,Furniture,Tables,Bush Advantage Collection Racetrack Conference...,254.526
1950,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-AP-10000358,Office Supplies,Appliances,Fellowes Basic Home/Office Series Surge Protec...,12.980
1951,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-BI-10004970,Office Supplies,Binders,"ACCOHIDE 3-Ring Binder, Blue, 1""",26.432
1952,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,TEC-PH-10003885,Technology,Phones,Cisco SPA508G,197.970
1953,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-LA-10001641,Office Supplies,Labels,Avery 518,18.900
1954,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,FUR-CH-10003379,Furniture,Chairs,Global Commerce Series High-Back Swivel/Tilt C...,1282.410
1955,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-AR-10004582,Office Supplies,Art,BIC Brite Liner Grip Highlighters,4.920
1956,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,TEC-AC-10002842,Technology,Accessories,WD My Passport Ultra 2TB Portable External Har...,238.000
1957,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,TEC-AC-10000109,Technology,Accessories,Sony Micro Vault Click 16 GB USB 2.0 Flash Drive,167.970
1958,CA-2018-157987,2018-02-09,2018-06-09,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009.0,East,OFF-PA-10003893,Office Supplies,Paper,Xerox 1962,17.120

Okay, clearly this is a result of an SQL query where the products sold are concatenated to the Order ID values. As such, there is a duplication of the the information relative to the orders. Either way the data is cleaned, although it might need some more splitting and combining to produce the desired analysis.

So, let's output these tables in several raw but cleaned sub-tables. I'll deal with these splits later on.

In [11]:
orders_data = sales_data[["Order ID", "Order Date", "Ship Date", "Customer ID", "Segment","Country","City","State","Postal Code","Region","Sales"]]
costumers_data = sales_data[["Customer ID", "Customer Name", "Segment", "Country","City","State", "Postal Code", "Region"]]
product_data = sales_data[["Product ID", "Category", "Sub-Category", "Product Name", "Sales"]]

Now let's wrangle the data a bit more to have datasets that are a bit more practical

Namely, let's split this cleaned dataset into tables that will be more practical for further analysis by:

**Product** , in order to conduct an ABC analysis, and profitability analysis by segment.

**Order** , in order to make market perdiction and understand the dynamics of order delivery.

**Customer**, in order to do some costumer segmentation and maybe understand our clientelle by segment / geography.

So let's prepare each one of these tables step-by-step.

# Orders Table

Let's start by preparing the orders table: Let's find out the total value per order and the nr of products per order.

In [12]:
order_value = orders_data.groupby("Order ID").Sales.agg("sum")
order_nr_of_products = orders_data.groupby("Order ID").Sales.agg("count")

In [13]:
orders_data = orders_data.drop(columns = ["Sales"])
orders_data = orders_data.drop_duplicates(subset='Order ID', keep='first')

In [14]:
orders_data = pd.merge(orders_data, order_value,
how='left', on="Order ID")
orders_data = pd.merge(orders_data, order_nr_of_products,
how='left', on="Order ID")
orders_data = orders_data.rename(columns = {"Sales_x":"Revenue", "Sales_y":'Nr_of_products'})

Now, after organizing and merging let's have a look on the current state of the table

In [15]:
orders_data.head()

,Order ID,Order Date,Ship Date,Customer ID,Segment,Country,City,State,Postal Code,Region,Revenue,Nr_of_products
0,CA-2017-152156,2017-08-11,2017-11-11,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,993.9000,2
1,CA-2017-138688,2017-12-06,2017-06-16,DV-13045,Corporate,United States,Los Angeles,California,90036.0,West,14.6200,1
2,US-2016-108966,2016-11-10,2016-10-18,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,979.9455,2
3,CA-2015-115812,2015-09-06,2015-06-14,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,3714.3040,7
4,CA-2018-114412,2018-04-15,2018-04-20,AA-10480,Consumer,United States,Concord,North Carolina,28027.0,South,15.5520,1

Now let's prepare some columns that are a result of other columns operations and that will be usefull later on.
 
 -Duration of shipping
 
 -Average price per order

In [16]:
orders_data["shipment_duration"] = orders_data["Ship Date"] - orders_data["Order Date"]
orders_data["Mean prod value"] = orders_data["Revenue"] / orders_data["Nr_of_products"]

In [17]:
orders_data.head()

,Order ID,Order Date,Ship Date,Customer ID,Segment,Country,City,State,Postal Code,Region,Revenue,Nr_of_products,shipment_duration,Mean prod value
0,CA-2017-152156,2017-08-11,2017-11-11,CG-12520,Consumer,United States,Henderson,Kentucky,42420.0,South,993.9000,2,92 days,496.950000
1,CA-2017-138688,2017-12-06,2017-06-16,DV-13045,Corporate,United States,Los Angeles,California,90036.0,West,14.6200,1,-173 days,14.620000
2,US-2016-108966,2016-11-10,2016-10-18,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,979.9455,2,-23 days,489.972750
3,CA-2015-115812,2015-09-06,2015-06-14,BH-11710,Consumer,United States,Los Angeles,California,90032.0,West,3714.3040,7,-84 days,530.614857
4,CA-2018-114412,2018-04-15,2018-04-20,AA-10480,Consumer,United States,Concord,North Carolina,28027.0,South,15.5520,1,5 days,15.552000

Right away we find something quite odd that we'll have to look into in the future. How come that we have negative shipping times?? 
For now let's just store this for further analysis later in another jupyter notebook.

In [18]:
%store orders_data

Stored 'orders_data' (DataFrame)

I also want a table that demostrates sales per day per region. The first thing to do is to know what regions we have.

In [19]:
orders_data["Region"].value_counts()

West       1587
East       1369
Central    1156
South       810
Name: Region, dtype: Int64

Now let's filter the dataframes by region and create time series of sales and nr of sold items in each one.

In [44]:
#create a custome fucntion to crunch the columns

def region_separator( df , region ):
    try:
        output = df[df.Region == region]
    except:
        print("Wrong inputs!")
    
    region_revenue = output.groupby("Order Date").Revenue.agg("sum")
    region_sales = output.groupby("Order Date").Nr_of_products.agg("sum")
    
    output = pd.concat([region_revenue,region_sales], axis = 1)
    
    
    output = output.rename(columns = {"Revenue" :  "R_"+ region ,"Nr_of_products" : "Vol_" + region  })
    return output

orders_west = region_separator(orders_data,"West")
orders_east = region_separator(orders_data,"East")
orders_north = region_separator(orders_data,"North")
orders_south = region_separator(orders_data,"South")

aux =pd.merge(orders_west,orders_east, how = "outer" , on= "Order Date")  
aux =pd.merge(aux,orders_north, how = "outer" , on= "Order Date")  
aux =pd.merge(aux,orders_south, how = "outer" , on= "Order Date") 
print(aux.isnull().sum())

region_time_series = aux.fillna(0)
#orders_south
region_time_series

%store region_time_series

R_West        324
Vol_West      324
R_East        380
Vol_East      380
R_North      1160
Vol_North    1160
R_South       562
Vol_South     562
dtype: int64
Stored 'region_time_series' (DataFrame)

# Products table

Let's try to find out the total volume of sales and total nr times the product was ordered. Sadly, we don't can't know for sure the unitary value of the product because we don't know it the total sale value represents one or more units.

In [18]:
product_total_sales  = product_data.groupby("Product ID").Sales.agg("sum")
product_nr_of_orders = product_data.groupby("Product ID").Sales.agg("count")

In [19]:
product_data = product_data.drop(columns = ["Sales"])
product_data = product_data.drop_duplicates(subset='Product ID', keep='first')

In [20]:
product_data = pd.merge(product_data, product_total_sales,
how='left', on="Product ID")
product_data = pd.merge(product_data, product_nr_of_orders,
how='left', on="Product ID")
product_data = product_data.rename(columns = {"Sales_x":"Total sales", "Sales_y":'Nr_of_orders'})

In [21]:
product_data.head()

,Product ID,Category,Sub-Category,Product Name,Total sales,Nr of orders
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,1263.957,4
1,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",10637.528,12
2,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,153.510,7
3,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,7242.768,8
4,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,301.968,5

In [22]:
%store product_data

Stored 'product_data' (DataFrame)